excerpt_separator: <!--more-->
url: https://www.inspircd.org

pagination:
  enabled: true
  per_page: 5
  sort_reverse: true
  title: :title (page :num)
  trail:
    after: 2
    before: 2

plugins:
- jekyll-feed
- jekyll-minifier
- jekyll-paginate-v2
- jekyll-redirect-from
- jekyll-sitemap
